### ISSUE TITLE
Cannot upload assets larger than 256MiB

### ISSUE THREAD

**Issue by brianwp3000** [PlayFab/MpsPowershell#4]
We need to break up the uploads into smaller block uploads instead of uploading the entire blob in a single request.

See https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks

**Comment by emrys90** [comment]
Is there any ETA on when this could be fixed?

**Comment by brianwp3000** [comment]
Fixed in module version 1.1.0
