### ISSUE TITLE
Ambiguous Parameter Set for New-PfBuild

### ISSUE THREAD

**Issue by dagrooms52** [PlayFab/MpsPowershell#9]
I'm trying to use `New-PfBuild` to create a Windows Process-mode build.

The docs imply this can be done with the following arguments with [CreateExpanded2](https://github.com/PlayFab/MpsPowershell/blob/807ad9e166bdf2dada5e79bc5fff13a0d2c876fe/MpsPowershell/docs/New-PfBuild.md#createexpanded2) being the equivalent of [Create2](https://github.com/PlayFab/MpsPowershell/blob/807ad9e166bdf2dada5e79bc5fff13a0d2c876fe/MpsPowershell/docs/New-PfBuild.md#create2), which has the option `-CreateBuildWithProcessBasedServerRequest`. If there is a different command I should use, please let me know.

The command I'm running has these arguments:
```ps1
New-PfBuild -BuildName <String> -GameAssetReferences <IAssetReferenceParams[]>
 -MultiplayerServerCountPerVM <Single> -Ports <IPort[]> -RegionConfigurations <IBuildRegionParams[]>
 -StartMultiplayerServerCommand <String>
```

When I run a command with these arguments filled, I get this error:
```
New-PfBuild : Parameter set cannot be resolved using the specified named parameters.
```

**Comment by brianwp3000** [comment]
I am able to reproduce this error. I also see that creating a Windows process-based build isn't properly documented, or else I probably would have realized this error myself :(

For a quick workaround you can use the `-IsOSPreview` flag. This flag will make your build run on a newer Windows VM image. More info on that [here](https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/servers/os-patch-updates), but the gist is that we actually recommend this for non-production builds.

Here's a working example of what I mean:

```powershell
PS C:\Users\bport> $gameAssets = @( @{ FileName = 'CrashingServerExample_v1_0.zip'; } )
PS C:\Users\bport> $regions = @( @{ 'MaxServers' = 0; 'Region' = 'AustraliaEast'; StandbyServers = 0; 'ScheduledStandbySettings' = $NULL } )
PS C:\Users\bport> $ports = @( @{ Name = 'tcp_port'; Protocol = 'TCP' }, @{ Name = 'udp_port'; Protocol = 'UDP' } )
PS C:\Users\bport> New-PfBuild -BuildName "bportTest" -GameAssetReferences $gameAssets -MultiplayerServerCountPerVM 1 -Ports $ports -RegionConfigurations $regions -StartMultiplayerServerCommand "crashingServerExample.exe" -IsOSPreview

Code Status
---- ------
200  OK
```

**Comment by dagrooms52** [comment]
Looks like that PR fixes this, thanks for the help!
